// src/app/[locale]/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { Providers } from './providers';

// Configuration de la police
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  axes: ["opsz"],
});

export const metadata : Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

// Composant principal (async pour récupérer params.locale)
export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers locale={params.locale}>{children}</Providers>
      </body>
    </html>
  );
}
